# Generated by Django 5.2.12 on 2026-04-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0005_dataset_document_dataset_documentversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestiontask',
            name='failed_section_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingestiontask',
            name='indexed_section_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingestiontask',
            name='strategy',
            field=models.CharField(choices=[('flat', 'Flat'), ('hierarchical', 'Hierarchical')], default='flat', max_length=32),
        ),
        migrations.AddField(
            model_name='ingestiontask',
            name='total_section_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DocumentSectionChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_index', models.PositiveIntegerField()),
                ('section_label', models.CharField(blank=True, default='', max_length=255)),
                ('section_path', models.CharField(blank=True, default='', max_length=512)),
                ('content', models.TextField()),
                ('vector_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_indexed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('start_offset', models.PositiveIntegerField(default=0)),
                ('end_offset', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_chunks', to='knowledgebase.document')),
            ],
            options={
                'ordering': ['section_index'],
                'unique_together': {('document', 'section_index')},
            },
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='section_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_chunks', to='knowledgebase.documentsectionchunk'),
        ),
    ]
