# Generated by Django 5.2.12 on 2026-05-04 21:15

from django.db import migrations, models


def _normalize_text(value):
    return " ".join(str(value or "").strip().split())


def _build_search_text(content, metadata):
    metadata = metadata or {}
    fields = (
        ("title", metadata.get("document_title")),
        ("doc_type", metadata.get("doc_type")),
        ("source_date", metadata.get("source_date")),
        ("dataset", metadata.get("dataset_name")),
        ("page", metadata.get("page_label")),
        ("section", metadata.get("section_label") or metadata.get("section_page_label")),
        ("section_path", metadata.get("section_path")),
    )
    lines = [f"{label}: {_normalize_text(value)}" for label, value in fields if _normalize_text(value)]
    body = _normalize_text(content)
    if body:
        lines.append(body)
    return "\n".join(lines)


def populate_search_text(apps, schema_editor):
    document_chunk_model = apps.get_model("knowledgebase", "DocumentChunk")
    section_chunk_model = apps.get_model("knowledgebase", "DocumentSectionChunk")

    batch = []
    for chunk in document_chunk_model.objects.order_by("id").iterator(chunk_size=200):
        chunk.search_text = _build_search_text(chunk.content, chunk.metadata)
        batch.append(chunk)
        if len(batch) >= 200:
            document_chunk_model.objects.bulk_update(batch, ["search_text"])
            batch = []
    if batch:
        document_chunk_model.objects.bulk_update(batch, ["search_text"])

    batch = []
    for section in section_chunk_model.objects.order_by("id").iterator(chunk_size=200):
        section.search_text = _build_search_text(section.content, section.metadata)
        batch.append(section)
        if len(batch) >= 200:
            section_chunk_model.objects.bulk_update(batch, ["search_text"])
            batch = []
    if batch:
        section_chunk_model.objects.bulk_update(batch, ["search_text"])


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgebase", "0006_ingestiontask_failed_section_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="search_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="documentsectionchunk",
            name="search_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(populate_search_text, migrations.RunPython.noop),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE knowledgebase_documentchunk "
                "ADD FULLTEXT INDEX kb_documentchunk_search_text_fts (search_text) WITH PARSER ngram"
            ),
            reverse_sql=(
                "ALTER TABLE knowledgebase_documentchunk "
                "DROP INDEX kb_documentchunk_search_text_fts"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE knowledgebase_documentsectionchunk "
                "ADD FULLTEXT INDEX kb_documentsectionchunk_search_text_fts (search_text) WITH PARSER ngram"
            ),
            reverse_sql=(
                "ALTER TABLE knowledgebase_documentsectionchunk "
                "DROP INDEX kb_documentsectionchunk_search_text_fts"
            ),
        ),
    ]
