# Generated by Django 5.2.12 on 2026-05-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgebase", "0007_documentchunk_search_text_and_fulltext"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestiontask",
            name="graph_document_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ingestiontask",
            name="graph_sync_error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ingestiontask",
            name="graph_sync_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestiontask",
            name="graph_sync_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestiontask",
            name="graph_sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="ingestiontask",
            name="graph_track_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="ingestiontask",
            name="current_step",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("parsing", "Parsing"),
                    ("chunking", "Chunking"),
                    ("indexing", "Indexing"),
                    ("graph_sync", "Graph sync"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=32,
            ),
        ),
    ]
