# Generated by Django 5.2.13 on 2026-05-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0008_ingestiontask_graph_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='File size in bytes'),
        ),
    ]
