# Generated by Django 5.2.14 on 2026-05-10 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0009_add_document_file_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('cleaning', 'Cleaning'), ('chunked', 'Chunked'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='uploaded', max_length=32),
        ),
        migrations.AlterField(
            model_name='ingestiontask',
            name='current_step',
            field=models.CharField(choices=[('queued', 'Queued'), ('parsing', 'Parsing'), ('cleaning', 'Cleaning'), ('chunking', 'Chunking'), ('indexing', 'Indexing'), ('graph_sync', 'Graph sync'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32),
        ),
        migrations.CreateModel(
            name='CleaningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rule_type', models.CharField(choices=[('clean_whitespace', 'Clean whitespace'), ('fix_encoding', 'Fix encoding'), ('normalize_quotes', 'Normalize quotes'), ('remove_bullets', 'Remove bullets'), ('group_broken_paragraphs', 'Group broken paragraphs'), ('remove_header_footer', 'Remove header/footer'), ('remove_page_numbers', 'Remove page numbers'), ('remove_boilerplate', 'Remove boilerplate'), ('remove_urls_emails', 'Remove URLs and emails'), ('dedup_exact', 'Deduplicate exact'), ('dedup_near', 'Deduplicate near'), ('fix_ocr_artifacts', 'Fix OCR artifacts'), ('normalize_financial_numbers', 'Normalize financial numbers')], db_index=True, max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cleaning_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCleaningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_applied', models.JSONField(blank=True, default=list)),
                ('issues_found', models.JSONField(blank=True, default=list)),
                ('quality_score', models.FloatField(default=0.0)),
                ('quality_signals', models.JSONField(blank=True, default=dict)),
                ('original_length', models.PositiveIntegerField(default=0)),
                ('cleaned_length', models.PositiveIntegerField(default=0)),
                ('dedup_count', models.PositiveIntegerField(default=0)),
                ('cleaned_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_results', to='knowledgebase.document')),
            ],
            options={
                'ordering': ['-cleaned_at', '-id'],
            },
        ),
    ]
