# Generated by Django 5.2.14 on 2026-05-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0010_add_cleaning_models_and_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA256 hash of the file content', max_length=64),
        ),
    ]
