# Generated by Django 5.2.14 on 2026-05-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_expand_riskextractiontask_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskreport',
            name='scope_type',
            field=models.CharField(choices=[('company', 'Company'), ('document', 'Document'), ('time_range', 'Time Range')], db_index=True, max_length=32),
        ),
    ]
