# Generated by Django 5.2.14 on 2026-05-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0010_ensure_active_rerank_model_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='input_price_per_million',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='output_price_per_million',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='price_currency',
            field=models.CharField(blank=True, default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='pricing_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='request_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='modelinvocationlog',
            name='input_cost',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='modelinvocationlog',
            name='input_unit_price_snapshot',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='modelinvocationlog',
            name='output_cost',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='modelinvocationlog',
            name='output_unit_price_snapshot',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='modelinvocationlog',
            name='provider_request_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='modelinvocationlog',
            name='raw_usage',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelinvocationlog',
            name='request_price_snapshot',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='modelinvocationlog',
            name='token_source',
            field=models.CharField(choices=[('provider', 'Provider'), ('estimated', 'Estimated'), ('none', 'None')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='modelinvocationlog',
            name='total_cost',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='modelinvocationlog',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('deepseek', 'DeepSeek'), ('dashscope', 'DashScope'), ('openai_compatible', 'OpenAI Compatible'), ('litellm', 'LiteLLM (Legacy)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='modelinvocationlog',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('deepseek', 'DeepSeek'), ('dashscope', 'DashScope'), ('openai_compatible', 'OpenAI Compatible'), ('litellm', 'LiteLLM (Legacy)')], default='openai_compatible', max_length=32),
        ),
    ]
