# Generated by Django 5.2.14 on 2026-05-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0012_restore_direct_provider_actives'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiteLLMSyncEvent',
        ),
    ]
