# Generated by Django 5.2.14 on 2026-05-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrecord',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('retried', 'Retried'), ('skipped', 'Skipped')], db_index=True, max_length=32),
        ),
    ]
