# Generated by Django 5.2.14 on 2026-05-10 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('metric_name', models.CharField(db_index=True, max_length=128)),
                ('condition', models.CharField(choices=[('gt', 'Greater than'), ('lt', 'Less than'), ('gte', 'Greater than or equal'), ('lte', 'Less than or equal'), ('eq', 'Equal')], max_length=8)),
                ('threshold', models.FloatField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('notification_channels', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('resolved', 'Resolved'), ('acknowledged', 'Acknowledged')], default='firing', max_length=16)),
                ('triggered_value', models.FloatField()),
                ('triggered_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ops.alertrule')),
            ],
            options={
                'ordering': ['-triggered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=128)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('collected_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-collected_at', '-id'],
                'indexes': [models.Index(fields=['metric_name', '-collected_at'], name='ops_metric_name_collected_idx')],
            },
        ),
    ]
